name: CI

on:
  push:
    branches: [ main, ci-changes ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install dependencies (Root)
        run: npm ci
      - name: Build package (Root)
        run: npm run build
      - name: Run tests
        run: npm run test --if-present
      - name: Dry run publish
        run: npm publish --dry-run
